
language: minimal
before_install:
  # https://github.com/containers/libpod/blob/master/install.md#ubuntu
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y software-properties-common uidmap
  - sudo add-apt-repository -y ppa:projectatomic/ppa
  - sudo apt-get update -qq
  - sudo apt-get -qq -y install podman

  # Hack podman's configuration files.
  # /etc/containers/registries.conf does not exist.
  # https://clouding.io/kb/en/how-to-install-and-use-podman-on-ubuntu-18-04/
  - ls -1 /etc/containers/registries.conf || true
  - sudo mkdir -p /etc/containers
  - echo -e "[registries.search]\nregistries = ['docker.io', 'quay.io']" | sudo tee /etc/containers/registries.conf
deploy:
  provider: script
  script: bash hack/build.sh quay
  on:
    branch: develop
